// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PacsApi.Context;

#nullable disable

namespace PacsApi.Migrations
{
    [DbContext(typeof(PacsDbContext))]
    [Migration("20260327062116_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("PacsApi.Models.Image", b =>
                {
                    b.Property<string>("SopInstanceUid")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessionNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcquisitionTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BitsAllocated")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BitsStored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyPartExamined")
                        .HasColumnType("TEXT");

                    b.Property<string>("CineRate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Columns")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConvolutionKernel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EchoTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlipAngle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FrameCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FrameOfReferenceUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FrameTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HighBit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageOrientationPatient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePositionPatient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("InstanceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kvp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modality")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotometricInterpretation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PixelRepresentation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PixelSpacing")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocolName")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepetitionTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("RescaleIntercept")
                        .HasColumnType("REAL");

                    b.Property<double?>("RescaleSlope")
                        .HasColumnType("REAL");

                    b.Property<int?>("Rows")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SamplesPerPixel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeriesInstanceUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SliceThickness")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SopClassUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransferSyntaxUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("XrayTubeCurrent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SopInstanceUid");

                    b.HasIndex("SopInstanceUid")
                        .IsUnique();

                    b.HasIndex("StudyInstanceUid");

                    b.HasIndex("SeriesInstanceUid", "InstanceNumber");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("PacsApi.Models.Patient", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgeString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExaminingDoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PatientBirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientSex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PatientId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PacsApi.Models.Series", b =>
                {
                    b.Property<string>("SeriesInstanceUid")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyPartExamined")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumberOfSeriesRelatedInstances")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientPosition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocolName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SendingAETitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SeriesDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SeriesTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SeriesInstanceUid");

                    b.HasIndex("SeriesInstanceUid")
                        .IsUnique();

                    b.HasIndex("StudyInstanceUid");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("PacsApi.Models.Study", b =>
                {
                    b.Property<string>("StudyInstanceUid")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessionNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExaminingDoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsAutoRouted")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsCdWritten")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsDicomSent")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsPrinted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberOfStudyRelatedInstances")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberOfStudyRelatedSeries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("PatientSize")
                        .HasColumnType("REAL");

                    b.Property<double?>("PatientWeight")
                        .HasColumnType("REAL");

                    b.Property<string>("PerformingPhysician")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReceivingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferringPhysicianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Report")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("SendingAETitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StudyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudyDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StudyTime")
                        .HasColumnType("TEXT");

                    b.HasKey("StudyInstanceUid");

                    b.HasIndex("PatientId");

                    b.HasIndex("StudyInstanceUid")
                        .IsUnique();

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("PacsApi.Models.Image", b =>
                {
                    b.HasOne("PacsApi.Models.Series", "Series")
                        .WithMany("Images")
                        .HasForeignKey("SeriesInstanceUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("PacsApi.Models.Series", b =>
                {
                    b.HasOne("PacsApi.Models.Study", "Study")
                        .WithMany("Series")
                        .HasForeignKey("StudyInstanceUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("PacsApi.Models.Study", b =>
                {
                    b.HasOne("PacsApi.Models.Patient", "Patient")
                        .WithMany("Studies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PacsApi.Models.Patient", b =>
                {
                    b.Navigation("Studies");
                });

            modelBuilder.Entity("PacsApi.Models.Series", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("PacsApi.Models.Study", b =>
                {
                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
