// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PacsApi.Context;

#nullable disable

namespace PacsApi.Migrations
{
    [DbContext(typeof(PacsDbContext))]
    [Migration("20260404071444_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PacsApi.Models.Image", b =>
                {
                    b.Property<string>("SopInstanceUid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccessionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AcquisitionTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BitsAllocated")
                        .HasColumnType("int");

                    b.Property<int?>("BitsStored")
                        .HasColumnType("int");

                    b.Property<string>("BodyPartExamined")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CineRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Columns")
                        .HasColumnType("int");

                    b.Property<string>("ConvolutionKernel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EchoTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlipAngle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FrameCount")
                        .HasColumnType("int");

                    b.Property<string>("FrameOfReferenceUid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrameTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HighBit")
                        .HasColumnType("int");

                    b.Property<string>("ImageOrientationPatient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePositionPatient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstanceNumber")
                        .HasColumnType("int");

                    b.Property<string>("Kvp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotometricInterpretation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PixelRepresentation")
                        .HasColumnType("int");

                    b.Property<string>("PixelSpacing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProtocolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepetitionTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("RescaleIntercept")
                        .HasColumnType("float");

                    b.Property<double?>("RescaleSlope")
                        .HasColumnType("float");

                    b.Property<int?>("Rows")
                        .HasColumnType("int");

                    b.Property<int?>("SamplesPerPixel")
                        .HasColumnType("int");

                    b.Property<string>("SeriesInstanceUid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SliceThickness")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SopClassUid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TransferSyntaxUid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XrayTubeCurrent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SopInstanceUid");

                    b.HasIndex("SopInstanceUid")
                        .IsUnique();

                    b.HasIndex("StudyInstanceUid");

                    b.HasIndex("SeriesInstanceUid", "InstanceNumber");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("PacsApi.Models.Patient", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AgeString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExaminingDoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PatientBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientSex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PacsApi.Models.Series", b =>
                {
                    b.Property<string>("SeriesInstanceUid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BodyPartExamined")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfSeriesRelatedInstances")
                        .HasColumnType("int");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProtocolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SendingAETitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SeriesDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeriesDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeriesNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SeriesTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SeriesInstanceUid");

                    b.HasIndex("SeriesInstanceUid")
                        .IsUnique();

                    b.HasIndex("StudyInstanceUid");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("PacsApi.Models.Study", b =>
                {
                    b.Property<string>("StudyInstanceUid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccessionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExaminingDoctorId")
                        .HasColumnType("int");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAutoRouted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCdWritten")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDicomSent")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPrinted")
                        .HasColumnType("bit");

                    b.Property<int?>("NumberOfStudyRelatedInstances")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfStudyRelatedSeries")
                        .HasColumnType("int");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("PatientSize")
                        .HasColumnType("float");

                    b.Property<double?>("PatientWeight")
                        .HasColumnType("float");

                    b.Property<string>("PerformingPhysician")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReceivingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferringPhysicianName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Report")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SendingAETitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StudyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudyDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StudyTime")
                        .HasColumnType("datetime2");

                    b.HasKey("StudyInstanceUid");

                    b.HasIndex("PatientId");

                    b.HasIndex("StudyInstanceUid")
                        .IsUnique();

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("PacsApi.Models.Image", b =>
                {
                    b.HasOne("PacsApi.Models.Series", "Series")
                        .WithMany("Images")
                        .HasForeignKey("SeriesInstanceUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("PacsApi.Models.Series", b =>
                {
                    b.HasOne("PacsApi.Models.Study", "Study")
                        .WithMany("Series")
                        .HasForeignKey("StudyInstanceUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("PacsApi.Models.Study", b =>
                {
                    b.HasOne("PacsApi.Models.Patient", "Patient")
                        .WithMany("Studies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PacsApi.Models.Patient", b =>
                {
                    b.Navigation("Studies");
                });

            modelBuilder.Entity("PacsApi.Models.Series", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("PacsApi.Models.Study", b =>
                {
                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
